# Generated by Django 3.2.5 on 2021-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
