# Generated by Django 3.2.5 on 2021-07-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210728_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, default=1, max_length=150),
        ),
    ]
